import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by Serwist; lint the source worker instead.
    "public/sw.js",
    "public/sw.js.map",
  ]),
  {
    rules: {
      // This rule reports intentional hydration and async loading effects across
      // the app. The correctness-focused hook rules remain enabled below it.
      "react-hooks/set-state-in-effect": "off",
    },
  },
]);

export default eslintConfig;
