export const PATHS = {
  HOME: "/",
  ANALYSIS: "/analysis",
  GET_STARTED: "/get-started",
  DOWNLOAD: "/download",
  CREATE_BUDGET: "/create-budget",
  BUDGET: (id: string) => `/budgets/${id}`,
  BOXES: "/boxes",
  PAYMENT_CARDS: "/payment-cards",
  PROFILE: "/profile",
  CATEGORIES: "/profile/categories",
  DEBTS: "/debts",
  DEBT: (id: string) => `/debts/${id}`,
  INSTALLMENTS: "/installments",
  INSTALLMENT_PLAN: (id: string) => `/installments/${id}`,
  CHECKS: "/checks",
  NOTES: "/notes",
  COMMITMENTS: "/commitments",
  PROJECTS: "/projects",
  PROJECT: (id: string) => `/projects/${id}`,
  PROJECT_ATTENDANCE: (id: string) => `/projects/${id}/attendance`,
  WORK_ATTENDANCE: "/projects/attendance",
  VENTURES: "/ventures",
  VENTURE: (id: string) => `/ventures/${id}`,
  INVITES: "/invites",
  PARTNER_INVITE: (token: string) => `/partner-invite/${token}`,
  TASKS: "/tasks",
  /** @deprecated use INSTALLMENTS */
  PLANNING: "/planning",
  ADMIN: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_DATABASE: "/admin/database",
  ADMIN_BACKUP: "/admin/backup",
  ADMIN_AUDIT: "/admin/audit",
  ADMIN_CONTENT: "/admin/content",
  ADMIN_APP: "/admin/app",
  ADMIN_VOICE: "/admin/voice",
} as const;
