export const PATHS = {
  HOME: "/",
  ANALYSIS: "/analysis",
  GET_STARTED: "/get-started",
  CREATE_BUDGET: "/create-budget",
  BUDGET: (id: string) => `/budgets/${id}`,
  BOXES: "/boxes",
  PROFILE: "/profile",
  CATEGORIES: "/profile/categories",
  DEBTS: "/debts",
  DEBT: (id: string) => `/debts/${id}`,
  INSTALLMENTS: "/installments",
  INSTALLMENT_PLAN: (id: string) => `/installments/${id}`,
  CHECKS: "/checks",
  NOTES: "/notes",
  COMMITMENTS: "/commitments",
  PROJECTS: "/projects",
  PROJECT: (id: string) => `/projects/${id}`,
  WORK_ATTENDANCE: "/projects/attendance",
  TASKS: "/tasks",
  /** @deprecated use INSTALLMENTS */
  PLANNING: "/planning",
} as const;
