export const PATHS = {
  LANDING: "/",
  HOME: "/app",
  PRICING: "/pricing",
  ANALYSIS: "/analysis",
  GET_STARTED: "/get-started",
  DOWNLOAD: "/download",
  CREATE_BUDGET: "/create-budget",
  BUDGET: (id: string) => `/budgets/${id}`,
  BOXES: "/boxes",
  PAYMENT_CARDS: "/payment-cards",
  PROFILE: "/profile",
  SETTINGS: "/settings",
  CATEGORIES: "/profile/categories",
  DEBTS: "/debts",
  DEBT: (id: string) => `/debts/${id}`,
  INSTALLMENTS: "/installments",
  INSTALLMENT_PLAN: (id: string) => `/installments/${id}`,
  CHECKS: "/checks",
  NOTES: "/notes",
  COMMITMENTS: "/commitments",
  PROJECTS: "/projects",
  PROJECT: (id: string) => `/projects/${id}`,
  PROJECT_ATTENDANCE: (id: string) => `/projects/${id}/attendance`,
  WORK_ATTENDANCE: "/projects/attendance",
  VENTURES: "/ventures",
  VENTURE: (id: string) => `/ventures/${id}`,
  BUSINESS: "/business",
  BUSINESS_DETAIL: (id: string) => `/business/${id}`,
  BUSINESS_STAFF: (id: string) => `/business/${id}/staff`,
  BUSINESS_ATTENDANCE: (id: string) => `/business/${id}/attendance`,
  BUSINESS_ATTENDANCE_ME: (id: string) => `/business/${id}/attendance/me`,
  BUSINESS_ATTENDANCE_SHIFTS: (id: string) => `/business/${id}/attendance/shifts`,
  BUSINESS_ATTENDANCE_REPORTS: (id: string) => `/business/${id}/attendance/reports`,
  BUSINESS_FINANCE: (id: string) => `/business/${id}/finance`,
  BUSINESS_EDIT_TRANSACTION: (id: string, budgetId: string) =>
    `/business/${id}/transactions/${budgetId}/edit`,
  BUSINESS_TRANSACTIONS: (id: string) => `/business/${id}/transactions`,
  BUSINESS_CREATE_TRANSACTION: (id: string) =>
    `/business/${id}/transactions/create`,
  BUSINESS_PETTY_CASH: (id: string) => `/business/${id}/petty-cash`,
  BUSINESS_INVITE: (token: string) => `/business-invite/${token}`,
  INVITES: "/invites",
  PARTNER_INVITE: (token: string) => `/partner-invite/${token}`,
  TASKS: "/tasks",
  /** @deprecated use INSTALLMENTS */
  PLANNING: "/planning",
  ADMIN: "/admin",
  ADMIN_USERS: "/admin/users",
  ADMIN_DATABASE: "/admin/database",
  ADMIN_BACKUP: "/admin/backup",
  ADMIN_AUDIT: "/admin/audit",
  ADMIN_AUTH_AUDIT: "/admin/auth-audit",
  ADMIN_LOGS: "/admin/logs",
  ADMIN_CONTENT: "/admin/content",
  ADMIN_LANDING: "/admin/landing",
  LANDING_PREVIEW: "/landing-preview",
  ADMIN_APP: "/admin/app",
  ADMIN_BANKS: "/admin/banks",
  ADMIN_VOICE: "/admin/voice",
  BANK_IMPORT: "/bank-import",
} as const;
